"""empty message

Revision ID: 900d7017adfb
Revises: 
Create Date: 2022-08-17 16:48:26.984409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900d7017adfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('show_name', sa.String(length=15), nullable=True, comment='用户名,显示名称'),
    sa.Column('username', sa.String(length=15), nullable=False, comment='用户名，注册登录账号'),
    sa.Column('password', sa.String(length=64), nullable=False, comment='用户登录密码'),
    sa.Column('phone', sa.String(length=12), nullable=False, comment='手机号码'),
    sa.Column('email', sa.String(length=30), nullable=True, comment='邮箱'),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('rdtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='用户状态,1：删除,0：存在'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
