"""empty message

Revision ID: 9f342dc989cb
Revises: b37a523168c3
Create Date: 2022-08-22 10:12:11.457225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f342dc989cb'
down_revision = 'b37a523168c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('article_ibfk_1', 'article', type_='foreignkey')
    op.create_foreign_key(None, 'article', 'users', ['user_id'], ['id'])
    op.drop_column('article', 'use_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('use_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.create_foreign_key('article_ibfk_1', 'article', 'users', ['use_id'], ['id'])
    op.drop_column('article', 'user_id')
    # ### end Alembic commands ###
