"""empty message

Revision ID: b37a523168c3
Revises: 81fcced7f084
Create Date: 2022-08-19 17:30:07.156296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b37a523168c3'
down_revision = '81fcced7f084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_copy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_copy',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=50), nullable=False),
    sa.Column('content', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False),
    sa.Column('pdatime', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('click_num', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('save_num', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('like_num', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('use_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['use_id'], ['users.id'], name='article_copy_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
